# Generated by Django 5.0.3 on 2024-03-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tusimbule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
